feat: Create top page
team-ondo/frontend pull request #6
Opened 2022-09-13 06:33 UTC by marimarimarietty

2022-09-13 10:17 UTC, Takashicc requested changes

2022-09-13 10:17 UTC, Takashicc commented on src/components/organisms/Livedata.tsx
> +  const [humidColor, setHumidColor] = useState<any>("rgb(255, 99, 132)");
Change the `<any>` to `<CanvasGradient | "rgb(255, 99, 132)">`

2022-09-13 10:17 UTC, Takashicc commented on src/pages/_app.tsx
>  function MyApp({ Component, pageProps }: AppProps) {
Are you using this file?

2022-09-13 10:17 UTC, Takashicc commented on src/pages/index.tsx
> +  const pageid = "index";
Are you using this file?

2022-09-13 12:08 UTC, marimarimarietty commented on src/pages/_app.tsx
>  function MyApp({ Component, pageProps }: AppProps) {
Yes, I need these files.

2022-09-13 12:09 UTC, marimarimarietty commented on src/pages/index.tsx
> +  const pageid = "index";
This is top page and I need this file.

2022-09-14 00:25 UTC, Takashicc approved these changes
LGTM!

2022-09-14 00:25 UTC, merged